apiVersion: v1
kind: Service
metadata:
  name: {{ include "wuda.fullname" . }}-database
  labels:
    {{- include "wuda.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
spec:
  type: {{ .Values.database.service.type }}
  ports:
  - port: {{ .Values.database.service.port }}
    targetPort: postgres
    protocol: TCP
    name: postgres
  selector:
    {{- include "wuda.database.selectorLabels" . | nindent 4 }}
