apiVersion: v1
kind: Secret
metadata:
  name: {{ include "wuda.fullname" . }}-secret
  labels:
    {{- include "wuda.labels" . | nindent 4 }}
type: Opaque
stringData:
  POSTGRES_PASSWORD: {{ .Values.database.env.postgresPassword | quote }}
  JWT_KEY: {{ .Values.secrets.jwtKey | quote }}
  SECRET_KEY: {{ .Values.secrets.sessionSecret | quote }}
