apiVersion: apps/v1
kind: Deployment
metadata:
  name: wuda-backend
  labels:
    helm.sh/chart: wuda-0.1.0
    app.kubernetes.io/name: wuda
    app.kubernetes.io/instance: wuda
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: wuda
      app.kubernetes.io/instance: wuda
      app.kubernetes.io/component: backend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: wuda
        app.kubernetes.io/instance: wuda
        app.kubernetes.io/component: backend
    spec:
      containers:
        - name: backend
          image: "ghcr.io/michaeleight/wuda-backend:latest"
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 5001
          env:
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: wuda-config
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: wuda-config
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: wuda-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: wuda-config
                  key: POSTGRES_HOST
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: wuda-config
                  key: PORT
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: wuda-secret
                  key: JWT_KEY
            - name: APP_PORT
              valueFrom:
                configMapKeyRef:
                  name: wuda-config
                  key: APP_PORT_BACKEND
            - name: APP_HOST
              valueFrom:
                configMapKeyRef:
                  name: wuda-config
                  key: APP_HOST_BACKEND
          livenessProbe:
            httpGet:
              path: /liveness
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /readiness
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
