apiVersion: v1
kind: Service
metadata:
  name: wuda-backend
  labels:
    helm.sh/chart: wuda-0.1.0
    app.kubernetes.io/name: wuda
    app.kubernetes.io/instance: wuda
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: backend
spec:
  type: ClusterIP
  ports:
    - port: 5001
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: wuda
    app.kubernetes.io/instance: wuda
    app.kubernetes.io/component: backend
