apiVersion: v1
kind: ConfigMap
metadata:
  name: wuda-config
  labels:
    helm.sh/chart: wuda-0.1.0
    app.kubernetes.io/name: wuda
    app.kubernetes.io/instance: wuda
    app.kubernetes.io/managed-by: Helm
data:
  POSTGRES_DB: "games"
  POSTGRES_USER: "board_games"
  POSTGRES_HOST: "wuda-database"
  PORT: "5432"
  BACKEND_HOSTNAME: "wuda-backend"
  BACKEND_PORT: "5001"
  APP_PORT_BACKEND: "5001"
  APP_HOST_BACKEND: "0.0.0.0"
  APP_PORT_FRONTEND: "8000"
  APP_HOST_FRONTEND: "0.0.0.0"
