apiVersion: v1
kind: Service
metadata:
  name: wuda-database
  labels:
    helm.sh/chart: wuda-0.1.0
    app.kubernetes.io/name: wuda
    app.kubernetes.io/instance: wuda
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: database
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: postgres
      protocol: TCP
      name: postgres
  selector:
    app.kubernetes.io/name: wuda
    app.kubernetes.io/instance: wuda
    app.kubernetes.io/component: database
