apiVersion: apps/v1
kind: Deployment
metadata:
  name: wuda-database
  labels:
    helm.sh/chart: wuda-0.1.0
    app.kubernetes.io/name: wuda
    app.kubernetes.io/instance: wuda
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: wuda
      app.kubernetes.io/instance: wuda
      app.kubernetes.io/component: database
  template:
    metadata:
      labels:
        app.kubernetes.io/name: wuda
        app.kubernetes.io/instance: wuda
        app.kubernetes.io/component: database
    spec:
      containers:
        - name: postgres
          image: "postgres:16"
          imagePullPolicy: IfNotPresent
          ports:
            - name: postgres
              containerPort: 5432
          env:
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: wuda-config
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: wuda-config
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: wuda-secret
                  key: POSTGRES_PASSWORD
