apiVersion: v1
kind: Service
metadata:
  name: wuda-frontend
  labels:
    helm.sh/chart: wuda-0.1.0
    app.kubernetes.io/name: wuda
    app.kubernetes.io/instance: wuda
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: frontend
spec:
  type: NodePort
  ports:
    - port: 8000
      targetPort: http
      protocol: TCP
      name: http
      nodePort: 30080
  selector:
    app.kubernetes.io/name: wuda
    app.kubernetes.io/instance: wuda
    app.kubernetes.io/component: frontend
