apiVersion: apps/v1
kind: Deployment
metadata:
  name: wuda-frontend
  labels:
    helm.sh/chart: wuda-0.1.0
    app.kubernetes.io/name: wuda
    app.kubernetes.io/instance: wuda
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: wuda
      app.kubernetes.io/instance: wuda
      app.kubernetes.io/component: frontend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: wuda
        app.kubernetes.io/instance: wuda
        app.kubernetes.io/component: frontend
    spec:
      containers:
        - name: frontend
          image: "ghcr.io/michaeleight/wuda-frontend:latest"
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8000
          env:
            - name: BACKEND_HOSTNAME
              valueFrom:
                configMapKeyRef:
                  name: wuda-config
                  key: BACKEND_HOSTNAME
            - name: BACKEND_PORT
              valueFrom:
                configMapKeyRef:
                  name: wuda-config
                  key: BACKEND_PORT
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: wuda-secret
                  key: SECRET_KEY
            - name: APP_PORT
              valueFrom:
                configMapKeyRef:
                  name: wuda-config
                  key: APP_PORT_FRONTEND
            - name: APP_HOST
              valueFrom:
                configMapKeyRef:
                  name: wuda-config
                  key: APP_HOST_FRONTEND
