apiVersion: v1
kind: Secret
metadata:
  name: wuda-secret
  labels:
    helm.sh/chart: wuda-0.1.0
    app.kubernetes.io/name: wuda
    app.kubernetes.io/instance: wuda
    app.kubernetes.io/managed-by: Helm
type: Opaque
stringData:
  POSTGRES_PASSWORD: "alamakota"
  JWT_KEY: "your-jwt-secret-key-change-me"
  SECRET_KEY: "your-session-secret-change-me"
